export {
  Bars3Icon,
  BookOpenIcon,
  ClipboardIcon,
  CalendarIcon,
  MagnifyingGlassIcon,
  LockClosedIcon,
  HomeIcon,
  EllipsisHorizontalIcon,
  ArrowPathIcon,
  XMarkIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  PencilIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  TrashIcon,
  CheckIcon,
  PlusIcon,
  Cog8ToothIcon,
  ShareIcon,
  ChatBubbleLeftIcon,
  AdjustmentsHorizontalIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
} from '@heroicons/react/24/solid';
