export {
  Bars3Icon,
  BookOpenIcon,
  ClipboardIcon,
  CalendarIcon,
  MagnifyingGlassIcon,
  LockClosedIcon,
  HomeIcon,
  EllipsisHorizontalIcon,
  ArrowPathIcon,
  XMarkIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  PencilIcon,
} from '@heroicons/react/24/solid';
